(() => {
  'use strict';
  const core=window.AICPUCoreV01;if(!core)throw new Error('AI CPU Core V0.1 not loaded');
  const STORAGE_SKILLS='aicpu-v0-skills',STORAGE_EPISODES='aicpu-v0-episodes',STORAGE_METRICS='aicpu-v0-metrics';
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const input=$('#commandInput'),messageList=$('#messageList'),flowList=$('#flowList');
  let skills=load(STORAGE_SKILLS,core.baseSkills),episodes=load(STORAGE_EPISODES,[]),metrics=load(STORAGE_METRICS,{cpu:0,agent:0,fail:0});
  metrics={cpu:Number(metrics.cpu)||0,agent:Number(metrics.agent)||0,fail:Number(metrics.fail)||0};
  function clone(v){return JSON.parse(JSON.stringify(v))}function load(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):clone(f)}catch{return clone(f)}}
  function save(){localStorage.setItem(STORAGE_SKILLS,JSON.stringify(skills));localStorage.setItem(STORAGE_EPISODES,JSON.stringify(episodes));localStorage.setItem(STORAGE_METRICS,JSON.stringify(metrics))}
  function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
  function addMessage(role,text,extra=''){const wrap=document.createElement('div');wrap.className=`message ${role}`;wrap.innerHTML=`<div class="avatar ${role==='assistant'?'cpu':'user'}">${role==='assistant'?'AI':'YOU'}</div><div class="message-body"><div class="bubble"></div><div class="message-meta">${role==='assistant'?'AI CPU Runtime V0.1':'Manual Command'}</div></div>`;wrap.querySelector('.bubble').textContent=text;if(extra)wrap.querySelector('.bubble').insertAdjacentHTML('beforeend',extra);messageList.appendChild(wrap);$('#chatScroll').scrollTop=$('#chatScroll').scrollHeight}
  function runtimeLines(items){return `<div class="runtime-block">${items.map(x=>`<div class="runtime-line ${x.kind||'ok'}">${esc(x.text)}</div>`).join('')}</div>`}
  function setStatus(type,text){const el=$('#runStatus');el.className='status-chip '+type;el.textContent=text}
  function topCandidates(match){return(match.ranked||[]).slice(0,3).map(x=>`${x.skill.id}:${x.score}`).join(' · ')||'-'}
  function renderFlow(cmd,match,runtime){const items=[{name:'PARSE',detail:`quality ${cmd.parse.quality}% • ${cmd.parse.valid?'VALID':'INVALID'}`,tag:cmd.parse.valid?'PASS':'FAIL'},{name:'STATE',detail:`${cmd.state} • ${cmd.observation||cmd.stateText||'-'}`,tag:'INPUT'},{name:'GOAL',detail:cmd.goal,tag:'TARGET'}];if(runtime.status===core.STATUS.DONE){const s=match.selected;items.push({name:'STRONG MATCH',detail:`${s.skill.id} • score ${s.score} • confidence ${match.confidence}%`,tag:'CPU'});for(const step of s.skill.steps||[])items.push({name:'EXECUTE',detail:step,tag:'STEP'});items.push({name:'VERIFY',detail:s.skill.verify||cmd.verify||'SUCCESS',tag:'PASS'},{name:'DONE',detail:'Known Skill simulation completed',tag:'RESULT'})}else{const label={PARSE_INVALID:'PARSE FAIL',SKILL_CONFLICT:'SKILL CONFLICT',WEAK_MATCH:'WEAK MATCH',NO_MATCH:'NO MATCH'}[runtime.reason]||runtime.reason;items.push({name:label,detail:`${match.classification} • candidates ${topCandidates(match)}`,tag:'STOP'},{name:'AGENT_NEEDED',detail:'หยุด CPU execution และส่ง State/Goal/Candidates ให้ Agent ภายนอก',tag:'AGENT'})}flowList.innerHTML=items.map((x,i)=>`<div class="flow-step ${i===items.length-1&&runtime.status===core.STATUS.DONE?'success':''}"><div class="flow-num">${i+1}</div><div><b>${esc(x.name)}</b><small>${esc(x.detail)}</small></div><span class="step-tag">${esc(x.tag)}</span></div>`).join('')}
  function renderTrace(cmd,match,runtime,episode){const trace={coreVersion:core.VERSION,timestamp:episode.time,parser:{valid:cmd.parse.valid,quality:cmd.parse.quality,errors:cmd.parse.errors,warnings:cmd.parse.warnings},state:cmd.state,observation:cmd.observation,goal:cmd.goal,matching:{classification:match.classification,confidence:match.confidence,reason:match.reason,candidates:episode.candidates},selectedSkill:episode.skill,runtime:{status:runtime.status,reason:runtime.reason,timeline:runtime.timeline},outcome:episode.outcome};$('#traceOutput').textContent=JSON.stringify(trace,null,2);$('#stateOutput').textContent=JSON.stringify(cmd,null,2)}
  function run(){const raw=input.value.trim();if(!raw){input.focus();return}addMessage('user',raw);const cmd=core.parseThaiCommand(raw),match=core.matchSkill(cmd,skills),runtime=core.decideRuntime(cmd,match),episode=core.createEpisode(cmd,match,runtime);episode.id=crypto.randomUUID?crypto.randomUUID():String(Date.now());$('#taskName').textContent=cmd.stateText||cmd.state||'Unknown Task';const agentNeeded=runtime.status===core.STATUS.AGENT_NEEDED;$('#agentCard').classList.toggle('active',agentNeeded);if(runtime.status===core.STATUS.DONE){const s=match.selected;metrics.cpu++;setStatus('done','DONE');addMessage('assistant',`STRONG_MATCH → ใช้ CPU Skill: ${s.skill.name}`,runtimeLines([{text:`Parser: ${cmd.parse.quality}% • ${cmd.state} → ${cmd.goal}`},{text:`Match: ${s.skill.id} • score ${s.score} • confidence ${match.confidence}%`},{text:`Why: ${s.reasons.map(r=>r.type).join(', ')}`},{text:`Workflow: ${(s.skill.steps||[]).join(' → ')}`},{text:`Verify: ${s.skill.verify||cmd.verify||'PASS'} → DONE`}]))}else{metrics.agent++;if(runtime.reason==='PARSE_INVALID')metrics.fail++;setStatus('agent','AGENT NEEDED');const title={PARSE_INVALID:'คำสั่งยังไม่ครบ จึงไม่ให้ CPU เดา',SKILL_CONFLICT:'พบ Skill ที่คะแนนใกล้กันเกินไป จึงหยุดก่อน',WEAK_MATCH:'มี Skill ใกล้เคียง แต่ความมั่นใจยังไม่พอ',NO_MATCH:'AI CPU ยังไม่มี Skill ที่รองรับปัญหานี้'}[runtime.reason]||'ต้องส่งต่อ Agent';addMessage('assistant',title,runtimeLines([{text:`Parser: ${cmd.parse.quality}% • Errors: ${cmd.parse.errors.join(', ')||'none'}`,kind:'warn'},{text:`State: ${cmd.state} → Goal: ${cmd.goal}`,kind:'warn'},{text:`Match class: ${match.classification} • confidence ${match.confidence}%`,kind:'warn'},{text:`Candidates: ${topCandidates(match)}`,kind:'warn'},{text:`${runtime.status} — CPU execution stopped`,kind:'warn'}]))}episodes.push(episode);if(episodes.length>300)episodes=episodes.slice(-300);save();renderFlow(cmd,match,runtime);renderTrace(cmd,match,runtime,episode);renderAll();input.value=''}
  function renderSkills(){$('#skillsGrid').innerHTML=skills.map(s=>`<article class="skill-card"><div class="skill-id">${esc(s.id)} · v${esc(s.version||'0.1')}</div><h3>${esc(s.name)}</h3><div class="skill-meta"><span class="mini-chip">${esc((s.states||[]).join(', ')||'keyword/explicit')}</span><span class="mini-chip">${esc((s.goals||[]).join(', ')||'any goal')}</span></div><ol class="skill-steps">${(s.steps||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol></article>`).join('');$('#skillCountBadge').textContent=skills.length;$('#metricSkills').textContent=skills.length}
  function renderMemory(){if(!episodes.length){$('#memoryTableWrap').innerHTML='<div class="empty-state">ยังไม่มี Memory — รันคำสั่งอย่างน้อย 1 ครั้ง</div>';return}const grouped={};for(const e of episodes){const key=`${e.state}|${e.goal}|${e.skill||e.matchClass}`;grouped[key]??={state:e.state,goal:e.goal,skill:e.skill||e.matchClass,uses:0,done:0,agent:0,total:0};const g=grouped[key];g.uses++;g.total+=Number(e.confidence)||0;e.outcome==='DONE'?g.done++:g.agent++}$('#memoryTableWrap').innerHTML=`<table class="memory-table"><thead><tr><th>STATE</th><th>GOAL</th><th>SKILL / MATCH</th><th>USES</th><th>DONE</th><th>AGENT</th><th>CONF.</th></tr></thead><tbody>${Object.values(grouped).reverse().map(g=>`<tr><td>${esc(g.state)}</td><td>${esc(g.goal)}</td><td>${esc(g.skill)}</td><td>${g.uses}</td><td>${g.done}</td><td>${g.agent}</td><td>${Math.round(g.total/g.uses)}%</td></tr>`).join('')}</tbody></table>`}
  function renderHistory(){const list=$('#historyList');if(!episodes.length){list.innerHTML='<div class="empty-state">ยังไม่มี Execution History</div>';return}list.innerHTML=episodes.slice().reverse().slice(0,50).map(e=>`<article class="history-item"><div><b>${esc(e.state)} → ${esc(e.goal)}</b><span>${new Date(e.time).toLocaleString('th-TH')}</span></div><div class="history-tags"><span>${esc(e.matchClass||'LEGACY')}</span><span>${esc(e.skill||'AGENT_NEEDED')}</span><span>${e.confidence||0}%</span><span>${esc(e.outcome)}</span></div></article>`).join('')}
  function renderTools(){const tools=[['HTTP_CLIENT','HTTP request / status'],['TOKEN_CHECK','ตรวจ token state'],['AUTH_REFRESH','จำลอง refresh token'],['PACKAGE_CHECK','ตรวจ dependency'],['SHELL_BUILD','จำลอง build command'],['FILE_CONVERT','จำลอง file conversion']];$('#toolsGrid').innerHTML=tools.map(([id,d])=>`<article class="skill-card"><div class="skill-id">${id}</div><h3>${d}</h3><div class="skill-meta"><span class="mini-chip">SIMULATION V0.1</span><span class="mini-chip">VPS-READY INTERFACE</span></div></article>`).join('')}
  function renderMetrics(){$('#metricCpu').textContent=metrics.cpu;$('#metricAgent').textContent=metrics.agent}function renderAll(){renderSkills();renderMemory();renderHistory();renderTools();renderMetrics()}
  function switchView(name){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('.content-view').forEach(x=>x.classList.remove('active'));$(`#view-${name}`)?.classList.add('active');$('#workspaceTitle').textContent={chat:'AI CPU Chat V0.1',skills:'CPU Skills',memory:'Skill Memory',history:'Experience History',tools:'Tool Registry'}[name]||'AI CPU'}
  function setSample(name){input.value=core.samples[name]||core.samples.auth;switchView('chat');input.focus()}
  $$('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('[data-sample]').forEach(b=>b.addEventListener('click',()=>setSample(b.dataset.sample)));$('#runBtn').addEventListener('click',run);input.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();run()}});$('#newTaskBtn').addEventListener('click',()=>{switchView('chat');input.value='';messageList.innerHTML='';flowList.innerHTML='<div class="flow-empty">ยังไม่มี Workflow — กด RUN เพื่อเริ่ม</div>';$('#taskName').textContent='รอคำสั่ง';setStatus('idle','IDLE');$('#traceOutput').textContent='// Trace จะปรากฏหลังรันคำสั่ง';$('#stateOutput').textContent='{\n  "state": "IDLE",\n  "goal": null\n}';$('#agentCard').classList.remove('active')});$('#mobileMenuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));document.addEventListener('click',e=>{if(innerWidth<=720&&!$('#sidebar').contains(e.target)&&e.target!==$('#mobileMenuBtn'))$('#sidebar').classList.remove('open')});$$('.canvas-tabs button').forEach(b=>b.addEventListener('click',()=>{$$('.canvas-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.canvas-pane').forEach(x=>x.classList.remove('active'));$(`#canvas-${b.dataset.canvas}`)?.classList.add('active')}));$('#openAddSkillBtn').addEventListener('click',()=>$('#addSkillDialog').showModal());$('#installSkillBtn').addEventListener('click',e=>{e.preventDefault();const id=$('#newSkillId').value.trim().toUpperCase().replace(/\s+/g,'_'),name=$('#newSkillName').value.trim(),keywords=$('#newSkillKeywords').value.split(',').map(x=>x.trim()).filter(Boolean),steps=$('#newSkillSteps').value.split(/\n/).map(x=>x.trim()).filter(Boolean);if(!id||!name||!keywords.length||!steps.length)return;skills=skills.filter(s=>s.id!==id);skills.push({id,name,version:'0.1',keywords,states:[],goals:[],steps,tools:['CUSTOM_TOOL'],verify:'SUCCESS'});save();renderAll();$('#addSkillDialog').close();$('#addSkillForm').reset()});renderAll();setSample('auth');
})();